### ISSUE TITLE
v4.8.5 - Compilation failure on OSX10.11 and older due to CLOCK_REALTIME

### ISSUE THREAD

**Issue by cjones051073** [xrootd/xrootd#846]
Version 4.8.5 fails to compile on OSX 10.11 and older, with errors like

```
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_science_xrootd/xrootd/work/xrootd-4.8.5/src/XrdSys/XrdSysPthread.cc:46:
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_science_xrootd/xrootd/work/xrootd-4.8.5/src/./XrdSys/XrdSysPthread.hh:152:17: error: use of undeclared identifier 'CLOCK_REALTIME'
  clock_gettime(CLOCK_REALTIME, &wait);
                ^
```

The previous release, 4.8.4, built fine on older OSX releases, back to OSX 10.7, so this is quite a regression for these older OS versions.

**Comment by cjones051073** [comment]
Full log for OSX10.11 build, if useful.

https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/68531/steps/install-port/logs/stdio

**Comment by cjones051073** [comment]
FWIW, the workaround I am now using can be seen here.

https://github.com/cjones051073/xrootd/commit/b2f04597d7497a2afc2e2a4bc066fff421f9d4ee

I have validated with a [little test application](https://github.com/xrootd/xrootd/files/2506147/time.cpp.txt) the two methods give consistent results. e.g.

```
 > clang++ ./time.cpp
 > ./a.out 
time1 1540296079731436000
time2 1540296079731497000
time1 1540296079731516000
time2 1540296079731526000
```

**Comment by abh3** [comment]
Hi Chris,

could you generate a pull request for this? Would it be possible to special case this so that your fix only applies to older version of MacOS and newer version use the current code.

Andy

**Comment by cjones051073** [comment]
Sure, I'll submit something tomorrow. 

The code already checks to see if CLOCK_REALTIME is defined and uses that as a means to determine what to use. If it is the current code is used, if not my fallback. I could though if you prefer change it to a test on the OSX version ?

**Comment by cjones051073** [comment]
FYI, you might want to take a look at

https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x

in particular the third answer down. It offers a number of different implementations, and perhaps the one using `gettimeofday` is preferable to you. It claims to be much faster. I don't know how important this is to you, nor what precision you require, so I leave this PR as is just for reference.

**Comment by abh3** [comment]
We've included a patch to resolve this problem for 4.9.0.
