### ISSUE TITLE
XrdPosix fails to compile with glibc 2.33 (2.32.9000)

### ISSUE THREAD

**Issue by ellert** [xrootd/xrootd#1315]
```
/builddir/build/BUILD/xrootd-5.0.2/src/XrdPosix/XrdPosix.cc: In function 'int XrdPosix_Fstat(int, stat*)':
/builddir/build/BUILD/xrootd-5.0.2/src/XrdPosix/XrdPosix.cc:379:27: error: '_STAT_VER' was not declared in this scope
  379 |           : Xunix.Fstat64(_STAT_VER, fildes, (struct stat64 *)buf));
      |                           ^~~~~~~~~
/builddir/build/BUILD/xrootd-5.0.2/src/XrdPosix/XrdPosix.cc: In function 'int XrdPosix_Lstat(const char*, stat*)':
/builddir/build/BUILD/xrootd-5.0.2/src/XrdPosix/XrdPosix.cc:563:27: error: '_STAT_VER' was not declared in this scope
  563 |           ? Xunix.Lstat64(_STAT_VER, path, (struct stat64 *)buf)
      |                           ^~~~~~~~~
/builddir/build/BUILD/xrootd-5.0.2/src/XrdPosix/XrdPosix.cc: In function 'int XrdPosix_Stat(const char*, stat*)':
/builddir/build/BUILD/xrootd-5.0.2/src/XrdPosix/XrdPosix.cc:891:26: error: '_STAT_VER' was not declared in this scope
  891 |           ? Xunix.Stat64(_STAT_VER, path, (struct stat64 *)buf)
      |                          ^~~~~~~~~
```
In glibc 2.32 and earlier _STAT_VER is defined in /usr/include/sys/stat.h (which includes /usr/include/bits/stat.h). However, in glibc 2.33 this define is dropped. The headers no longer redirects the calls to the kernel functions, but there are implementations in glibc.

I do not know how to fix this, is it sufficient to do
```
#ifndef _STAT_VER
#define _STAT_VER <some value> /* What value? */
#endif
```
Or does it need morc complicates changes?

**Comment by xrootd-dev** [comment]
Hi Mattias,

It just eans we need to replce this with the 2.33 equivalent. I assume 
you installed it manually because this release won't be officially 
available until February 2021. Do you know which Linux distribution it 
will appear in first?

Andy

**Comment by ellert** [comment]
The compilation started failing on Fedora 34/Fedora Rawhide. Fedora 34 is scheduled for 2021-04-20.
https://koschei.fedoraproject.org/package/xrootd?collection=f34

It can be reproduced using a Fedora Rawhide mockbuild:
mock --root fedora-rawhide-x86_64 xrootd-5.0.2-1.fc33.src.rpm

**Comment by abh3** [comment]
Ah, those are hard to come by. Anyway I can login to a Fedora 34 machine?

**Comment by ellert** [comment]
You don't need a Fedora 34 machine to build for Fedora 34. A mock chroot environment is sufficient.

**Comment by simonmichal** [comment]
This is fixed in 5298c732c394d7ac3c24abc7d01a4631f573e692

**Comment by ellert** [comment]
I applied the commit as a patch for the Fedora Rawhide build and it builds again.
https://src.fedoraproject.org/rpms/xrootd/c/369a165341d142ceff52dc1324fe15735246ead8?branch=master
https://koschei.fedoraproject.org/package/xrootd?collection=f34

Candidate commit for stable?

**Comment by simonmichal** [comment]
@ellert : thanks a lot! we will have `5.1.0` soonish and it will be definitely included.
