### ISSUE TITLE
XRootD python binding are build in debug mode

### ISSUE THREAD

**Issue by smuzaffar** [xrootd/xrootd#1807]
Hi,
  Although we use `cmake -DCMAKE_BUILD_TYPE=Release` to configure/build xrootd but looks like the python binding are build in debug mode (see the `-DNDEBUG -g` flags in [a] below). Any specific reason for this?

Thanks, --Shahzad
```
cc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall --std=c++14 -fPIC -Ixrootd/5.5.1-7737cc2c22e178882ee7e369b85a17e2/xrootd-5.5.1/src -Ixrootd/5.5.1-7737cc2c22e178882ee7e369b85a17e2/build/src -Iexternal/python3/3.9.14-94e2a0b6aa9f396a5858e80362919be6/include/python3.9 -c xrootd/5.5.1-7737cc2c22e178882ee7e369b85a17e2/xrootd-5.5.1/bindings/python/src/PyXRootDCopyProcess.cc -o build/temp.linux-x86_64-3.9xrootd/5.5.1-7737cc2c22e178882ee7e369b85a17e2/xrootd-5.5.1/bindings/python/src/PyXRootDCopyProcess.o -g
cc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall --std=c++14 -fPIC -Ixrootd/5.5.1-7737cc2c22e178882ee7e369b85a17e2/xrootd-5.5.1/src -Ixrootd/5.5.1-7737cc2c22e178882ee7e369b85a17e2/build/src -Iexternal/python3/3.9.14-94e2a0b6aa9f396a5858e80362919be6/include/python3.9 -c xrootd/5.5.1-7737cc2c22e178882ee7e369b85a17e2/xrootd-5.5.1/bindings/python/src/PyXRootDCopyProgressHandler.cc -o build/temp.linux-x86_64-3.9xrootd/5.5.1-7737cc2c22e178882ee7e369b85a17e2/xrootd-5.5.1/bindings/python/src/PyXRootDCopyProgressHandler.o -g
```

**Comment by amadio** [comment]
Hi @smuzaffar, `-DNDEBUG` is for disabling assertions, so that looks fine. As for `-g`, I believe may be needed so that the `*-debuginfo` RPMs can be built, but @simonmichal can correct me if I'm wrong. I'd say this is more like `RelWithDebInfo` than `Debug` mode. If the default release flags for XRootD are not what you want, you can still override them by setting `-DCMAKE_CXX_FLAGS_RELEASE=...` when calling CMake.

**Comment by simonmichal** [comment]
I think it might be because of:
https://github.com/xrootd/xrootd/blob/016942782ef5fb15f906bb0fab84270f199015c8/bindings/python/setup.py.in#L129

we should make this dependant on the build type in cmake

**Comment by amadio** [comment]
I had a look at this last week (at least at removing that `-g` from `extra_compile_args`). However, it seems that even though we pass down `CMAKE_CXX_FLAGS` via `PY_CXX_FLAGS`, during the builds I am not seeing the flags appear. I will further investigate things to ensure `CMAKE_CXX_FLAGS` are used also for the Python bindings, then we can rely on `-g` being there when `CMAKE_BUILD_TYPE` is `RelWithDebInfo` or `Debug`, rather than adding it to `extra_compile_args`.

**Comment by amadio** [comment]
There is a difference in behavior after commit 9e01966ff7973fa88cdd30ac20c2181bb76d8e5a which stops propagation of `CXXFLAGS` to the build of Python bindings in certain cases. Reverting this commit fixed a problem I observed while testing a build on macOS (where I am using Python 3.9), where the flags for setting the C++ standard were not being propagated, leading to the error below:
```
$ cd bindings/python
$ python3 -m pip wheel --verbose .
...
  /usr/bin/gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/tmp/xrootd/xrootd/src -I/tmp/xrootd/xrootd_build/src -I/Users/Shared/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-7971d/arm64-mac12-clang131-opt/include/python3.9 -c /tmp/xrootd/xrootd/bindings/python/src/PyXRootDCopyProcess.cc -o build/temp.macosx-12.4-arm64-3.9/tmp/xrootd/xrootd/bindings/python/src/PyXRootDCopyProcess.o -g
  In file included from /tmp/xrootd/xrootd/bindings/python/src/PyXRootDCopyProcess.cc:26:
  In file included from /tmp/xrootd/xrootd/bindings/python/src/PyXRootDCopyProcess.hh:30:
  In file included from /tmp/xrootd/xrootd/src/XrdCl/XrdClCopyProcess.hh:29:
  In file included from /tmp/xrootd/xrootd/src/XrdCl/XrdClXRootDResponses.hh:22:
  /tmp/xrootd/xrootd/src/XrdCl/XrdClBuffer.hh:50:22: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
        Buffer( Buffer &&buffer )
                       ^
  /tmp/xrootd/xrootd/src/XrdCl/XrdClBuffer.hh:58:33: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
        Buffer& operator=( Buffer && buffer )
                                  ^
  /tmp/xrootd/xrootd/src/XrdCl/XrdClBuffer.hh:249:26: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
        void Steal( Buffer &&buffer )
                           ^
  In file included from /tmp/xrootd/xrootd/bindings/python/src/PyXRootDCopyProcess.cc:26:
  In file included from /tmp/xrootd/xrootd/bindings/python/src/PyXRootDCopyProcess.hh:30:
  In file included from /tmp/xrootd/xrootd/src/XrdCl/XrdClCopyProcess.hh:29:
  /tmp/xrootd/xrootd/src/XrdCl/XrdClXRootDResponses.hh:289:16: error: no template named 'tuple' in namespace 'std'
    typedef std::tuple<std::string, std::string> xattr_t;
            ~~~~~^
... (many more errors follow due to C++14 not being used)
```

In part, build/install failures have been masked by the fact that `make install` didn't fail (i.e. returned 0) even when the call to `pip install` for the Python bindings failed, which I am fixing in #1822, by checking the return status of the installation of the Python bindings.

On Linux, using Python 3.10 and regardless of commit 9e01966ff7973fa88cdd30ac20c2181bb76d8e5a being reverted or not I don't see the `CMAKE_CXX_FLAGS` in the wheel build flags, even when I use `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ...` to configure (at least `-O2 -g` should have been there). I also added `-DCMAKE_CXX_FLAGS=-fno-omit-frame-pointer` and that flag doesn't appear in the compilation either.

I think it may be worth the effort to write a more modern setup for building/installing the Python bindings, so that we restore consistent behavior across the various versions of Python and OSs that are supported.

@simonmichal What do you think?
