### ISSUE TITLE
Can't build xrootd with openssl from Homebrew (MacOS)

### ISSUE THREAD

**Issue by oshadura** [xrootd/xrootd#1558]
I was trying to build recent tags of xrootd as well `master` branch on MacOs with openssl 1.1.1l available from Homebrew. My build command is: 

```
cmake .. -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib -DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl@1.1/include
```
I got:
```
Consolidate compiler generated dependencies of target XrdCryptossl-5
[ 97%] Building CXX object src/CMakeFiles/XrdCryptossl-5.dir/XrdCrypto/XrdCryptosslCipher.cc.o
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:140:12: error: static declaration of 'DH_compute_key_padded' follows non-static declaration
static int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh)
           ^
/usr/local/opt/openssl@1.1/include/openssl/dh.h:153:5: note: previous declaration is here
int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh);
    ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:143:12: error: member access into incomplete type 'DH' (aka 'dh_st')
    rv = dh->meth->compute_key(key, pub_key, dh);
           ^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'dh_st'
typedef struct dh_st DH;
               ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:146:26: error: member access into incomplete type 'DH' (aka 'dh_st')
    pad = BN_num_bytes(dh->p) - rv;
                         ^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'dh_st'
typedef struct dh_st DH;
               ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:541:35: error: call to 'DH_compute_key_padded' is ambiguous
                           ltmp = DH_compute_key_padded((unsigned char *)ktmp,bnpub,fDH);
                                  ^~~~~~~~~~~~~~~~~~~~~
/usr/local/opt/openssl@1.1/include/openssl/dh.h:153:5: note: candidate function
int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh);
    ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:140:12: note: candidate function
static int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh)
           ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:715:23: error: call to 'DH_compute_key_padded' is ambiguous
               ltmp = DH_compute_key_padded((unsigned char *)ktmp,bnpub,fDH);
                      ^~~~~~~~~~~~~~~~~~~~~
/usr/local/opt/openssl@1.1/include/openssl/dh.h:153:5: note: candidate function
int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh);
    ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:140:12: note: candidate function
static int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh)
           ^
5 errors generated.
```
```

**Comment by simonmichal** [comment]
@oshadura : thanks for reporting this problem, I will have a look.

It seems it must be related to the setup of the build node as our builds our green:
https://gitlab.cern.ch/dss/xrootd/-/jobs/17647570

**Comment by oshadura** [comment]
Yup, it looks like it could be related  to version of openssl: I am using 1.1.1l  and in your setup you are still using 1.0.2t...

**Comment by oshadura** [comment]
I also tried to build with openssl 3.0.0 using`cmake .. -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl@3/lib/libcrypto.3.dylib -DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl@3/lib/libssl.3.dylib -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl@3/include` and also unsuccessfully:

```
Consolidate compiler generated dependencies of target XrdUtils
[  0%] Building CXX object src/CMakeFiles/XrdUtils.dir/XrdCrypto/XrdCryptosslRSA.cc.o
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslRSA.cc:504:19: error: no matching function for call to 'RSA_private_encrypt'
      if ((lout = RSA_private_encrypt(lc, (unsigned char *)&in[kk],
                  ^~~~~~~~~~~~~~~~~~~
/usr/local/opt/openssl@3/include/openssl/rsa.h:285:5: note: candidate function not viable: 4th argument ('const struct rsa_st *') would lose const qualifier
int RSA_private_encrypt(int flen, const unsigned char *from, unsigned char *to,
    ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslRSA.cc:555:19: error: no matching function for call to 'RSA_public_encrypt'
      if ((lout = RSA_public_encrypt(lc, (unsigned char *)&in[kk],
                  ^~~~~~~~~~~~~~~~~~
/usr/local/opt/openssl@3/include/openssl/rsa.h:282:5: note: candidate function not viable: 4th argument ('const struct rsa_st *') would lose const qualifier
int RSA_public_encrypt(int flen, const unsigned char *from, unsigned char *to,
    ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslRSA.cc:605:19: error: no matching function for call to 'RSA_private_decrypt'
      if ((lout = RSA_private_decrypt(lcmax, (unsigned char *)&in[kk],
                  ^~~~~~~~~~~~~~~~~~~
/usr/local/opt/openssl@3/include/openssl/rsa.h:291:5: note: candidate function not viable: 4th argument ('const struct rsa_st *') would lose const qualifier
int RSA_private_decrypt(int flen, const unsigned char *from, unsigned char *to,
    ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslRSA.cc:654:19: error: no matching function for call to 'RSA_public_decrypt'
      if ((lout = RSA_public_decrypt(lcmax, (unsigned char *)&in[kk],
                  ^~~~~~~~~~~~~~~~~~
/usr/local/opt/openssl@3/include/openssl/rsa.h:288:5: note: candidate function not viable: 4th argument ('const struct rsa_st *') would lose const qualifier
int RSA_public_decrypt(int flen, const unsigned char *from, unsigned char *to,
    ^
4 errors generated.
make[2]: *** [src/CMakeFiles/XrdUtils.dir/XrdCrypto/XrdCryptosslRSA.cc.o] Error 1
make[1]: *** [src/CMakeFiles/XrdUtils.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by simonmichal** [comment]
In order to build it with openssl3 you need to pass `-DWITH_OPENSSL3=TRUE` to cmake. Please note this is considered experimental and might crash.

**Comment by simonmichal** [comment]
@oshadura : sorry for the delay, I finally had time to give it a try. For me it works just fine with `1.1.1l` ^^, here's my cmake incantation:
```
cmake -DOPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl\@1.1/1.1.1l_1/include/ -DOPENSSL_SSL_LIBRARY=/usr/local/Cellar/openssl\@1.1/1.1.1l_1/lib/libssl.1.1.dylib  -DOPENSSL_CRYPTO_LIBRARY=/usr/local/Cellar/openssl\@1.1/1.1.1l_1/lib/libcrypto.1.1.dylib  ..
```

and here's my openssl installation with brew:
```
$ brew list openssl@1.1
/usr/local/Cellar/openssl@1.1/1.1.1l_1/.bottle/etc/ (7 files)
/usr/local/Cellar/openssl@1.1/1.1.1l_1/bin/c_rehash
/usr/local/Cellar/openssl@1.1/1.1.1l_1/bin/openssl
/usr/local/Cellar/openssl@1.1/1.1.1l_1/include/openssl/ (104 files)
/usr/local/Cellar/openssl@1.1/1.1.1l_1/lib/libcrypto.1.1.dylib
/usr/local/Cellar/openssl@1.1/1.1.1l_1/lib/libssl.1.1.dylib
/usr/local/Cellar/openssl@1.1/1.1.1l_1/lib/engines-1.1/ (2 files)
/usr/local/Cellar/openssl@1.1/1.1.1l_1/lib/pkgconfig/ (3 files)
/usr/local/Cellar/openssl@1.1/1.1.1l_1/lib/ (4 other files)
/usr/local/Cellar/openssl@1.1/1.1.1l_1/share/doc/ (3971 files)
/usr/local/Cellar/openssl@1.1/1.1.1l_1/share/man/ (3971 files)
```

Looking at your error message the `HAVE_DH_PADDED_FUNC` macro is not defined:
https://github.com/xrootd/xrootd/blob/253acea4cf51ff221d23e82b0f667a61de562785/src/XrdCrypto/XrdCryptosslCipher.cc#L136-L154

which is weird because in my openssl installation the signature is present:
```
$ pwd
/usr/local/Cellar/openssl@1.1/1.1.1l_1/include/openssl
$ grep -r DH_compute_key_padded .
./dh.h:int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh);
```

Could you check if in your case the routine declarations is present in the openssl header files?

**Comment by oshadura** [comment]
Hi @simonmichal,

The same for me: 
```
  │  /usr/lo/Ce/openssl@1.1/1.1.1l_1/include/openssl  grep -r DH_compute_key_padded .                                                    ✔ │ 14:05:47 
./dh.h:int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh);
  │  /usr/lo/Ce/openssl@1.1/1.1.1l_1/include/openssl 
```
I think the problem is that `DH_compute_key_padded` is declared as nonstatic and you have implemented it as static in xrootd ?:
```
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:140:12: error: static declaration of 'DH_compute_key_padded' follows non-static declaration
static int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh)
           ^
/usr/local/opt/openssl@1.1/include/openssl/dh.h:153:5: note: previous declaration is here
int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh);
    ^
```
See more in VERBOSE mode:
```
[ 97%] Building CXX object src/CMakeFiles/XrdCryptossl-5.dir/XrdCrypto/XrdCryptosslCipher.cc.o
cd /Users/oshadura/CERN_sources/xrootd/builds/src && /Library/Developer/CommandLineTools/usr/bin/c++ -DHAVE_ATOMICS -DHAVE_CRYPT -DHAVE_CURL_MULTI_WAIT -DHAVE_FSTATAT -DHAVE_GETIFADDRS -DHAVE_LIBZ -DHAVE_NAMEINFO -DHAVE_READLINE -DHAVE_SSL -DHAVE_STRLCPY -DHAVE_XML2 -DHAVE_XRDCRYPTO -DLT_MODULE_EXT=\".dylib\" -DXRDPLUGIN_SOVERSION=\"5\" -DXrdCryptossl_5_EXPORTS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/Users/oshadura/CERN_sources/xrootd/src/.. -I/Users/oshadura/CERN_sources/xrootd/src/. -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/uuid -I/Users/oshadura/CERN_sources/xrootd/src -I/Users/oshadura/CERN_sources/xrootd/builds/src -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Kerberos.framework/Headers -Wno-deprecated-declarations -O2 -g -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk -fPIC -std=gnu++14 -MD -MT src/CMakeFiles/XrdCryptossl-5.dir/XrdCrypto/XrdCryptosslCipher.cc.o -MF CMakeFiles/XrdCryptossl-5.dir/XrdCrypto/XrdCryptosslCipher.cc.o.d -o CMakeFiles/XrdCryptossl-5.dir/XrdCrypto/XrdCryptosslCipher.cc.o -c /Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:140:12: error: static declaration of 'DH_compute_key_padded' follows non-static declaration
static int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh)
           ^
/usr/local/opt/openssl@1.1/include/openssl/dh.h:153:5: note: previous declaration is here
int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh);
    ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:143:12: error: member access into incomplete type 'DH' (aka 'dh_st')
    rv = dh->meth->compute_key(key, pub_key, dh);
           ^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'dh_st'
typedef struct dh_st DH;
               ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:146:26: error: member access into incomplete type 'DH' (aka 'dh_st')
    pad = BN_num_bytes(dh->p) - rv;
                         ^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'dh_st'
typedef struct dh_st DH;
               ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:541:35: error: call to 'DH_compute_key_padded' is ambiguous
                           ltmp = DH_compute_key_padded((unsigned char *)ktmp,bnpub,fDH);
                                  ^~~~~~~~~~~~~~~~~~~~~
/usr/local/opt/openssl@1.1/include/openssl/dh.h:153:5: note: candidate function
int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh);
    ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:140:12: note: candidate function
static int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh)
           ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:715:23: error: call to 'DH_compute_key_padded' is ambiguous
               ltmp = DH_compute_key_padded((unsigned char *)ktmp,bnpub,fDH);
                      ^~~~~~~~~~~~~~~~~~~~~
/usr/local/opt/openssl@1.1/include/openssl/dh.h:153:5: note: candidate function
int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh);
    ^
/Users/oshadura/CERN_sources/xrootd/src/XrdCrypto/XrdCryptosslCipher.cc:140:12: note: candidate function
static int DH_compute_key_padded(unsigned char *key, const BIGNUM *pub_key, DH *dh)
           ^
5 errors generated.
make[2]: *** [src/CMakeFiles/XrdCryptossl-5.dir/XrdCrypto/XrdCryptosslCipher.cc.o] Error 1
make[1]: *** [src/CMakeFiles/XrdCryptossl-5.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by simonmichal** [comment]
Well, the problem is that if `DH_compute_key_padded ` signature exists in the included openssl header files `cmake` should define `HAVE_DH_PADDED_FUNC`:
https://github.com/xrootd/xrootd/blob/253acea4cf51ff221d23e82b0f667a61de562785/cmake/FindOpenSSL.cmake#L85-L89
and then the part of code where you getting your compilation error wouldn't be included in compilation at all.

Now the big question is why it sin't ;-) could add check if the cmake `check_function_exists` and `check_symbol_exists` is called and if it finds anything?

**Comment by oshadura** [comment]
You are right it is empty in cmake cache: 
```
  │  ~/CERN_sources/xrootd/builds │   stable-5.3.x ?1  grep -r HAVE_DH_PADDED_FUNC .                                                   ✔ │ 16:44:52 
./CMakeCache.txt:HAVE_DH_PADDED_FUNC:INTERNAL= 
```

**Comment by oshadura** [comment]
Checking  CMakeFiles/CMakeError.log I see next:
```
....
Determining if the function DH_compute_key_padded exists failed with the following output:
Change Dir: /Users/oshadura/CERN_sources/xrootd/builds/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_7c697/fast && /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_7c697.dir/build.make CMakeFiles/cmTC_7c697.dir/build
Building C object CMakeFiles/cmTC_7c697.dir/CheckFunctionExists.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=DH_compute_key_padded -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk -MD -MT CMakeFiles/cmTC_7c697.dir/CheckFunctionExists.c.o -MF CMakeFiles/cmTC_7c697.dir/CheckFunctionExists.c.o.d -o CMakeFiles/cmTC_7c697.dir/CheckFunctionExists.c.o -c /usr/local/Cellar/cmake/3.21.2/share/cmake/Modules/CheckFunctionExists.c
make[1]: *** No rule to make target `/usr/local/opt/openssl@1.1/lib/libssl.1.dylib', needed by `cmTC_7c697'.  Stop.
make: *** [cmTC_7c697/fast] Error 2



Determining if the DH_compute_key_padded exist failed with the following output:
Change Dir: /Users/oshadura/CERN_sources/xrootd/builds/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_01278/fast && /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_01278.dir/build.make CMakeFiles/cmTC_01278.dir/build
Building C object CMakeFiles/cmTC_01278.dir/CheckSymbolExists.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk -MD -MT CMakeFiles/cmTC_01278.dir/CheckSymbolExists.c.o -MF CMakeFiles/cmTC_01278.dir/CheckSymbolExists.c.o.d -o CMakeFiles/cmTC_01278.dir/CheckSymbolExists.c.o -c /Users/oshadura/CERN_sources/xrootd/builds/CMakeFiles/CMakeTmp/CheckSymbolExists.c
In file included from /Users/oshadura/CERN_sources/xrootd/builds/CMakeFiles/CMakeTmp/CheckSymbolExists.c:2:
/usr/local/opt/openssl@1.1/include/openssl/dh.h:13:11: fatal error: 'openssl/opensslconf.h' file not found
# include <openssl/opensslconf.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_01278.dir/CheckSymbolExists.c.o] Error 1
make: *** [cmTC_01278/fast] Error 2


File /Users/oshadura/CERN_sources/xrootd/builds/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include </usr/local/opt/openssl@1.1/include/openssl/dh.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef DH_compute_key_padded
  return ((int*)(&DH_compute_key_padded))[argc];
#else
  (void)argc;
  return 0;
#endif
}
```

**Comment by oshadura** [comment]
I rebuild totally from scratch and now it is crashing in a different way :D
```
[ 98%] Building CXX object src/CMakeFiles/XrdFfs.dir/XrdFfs/XrdFfsDent.cc.o
In file included from /Users/oshadura/CERN_sources/xrootd/bindings/python/src/PyXRootDFile.cc:25:
In file included from /Users/oshadura/CERN_sources/xrootd/bindings/python/src/PyXRootD.hh:28:
In file included from /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h:33:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/stdio.h:107:15: fatal error: 'stdio.h' file not found
#include_next <stdio.h>
              ^~~~~~~~~
[ 98%] Built target xrdadler32
[ 98%] Building CXX object src/CMakeFiles/XrdSsi-5.dir/XrdSsi/XrdSsiFileReq.cc.o
[ 98%] Building CXX object src 
```
I think using Docker or switching to other machine will be my best choice

**Comment by simonmichal** [comment]
@oshadura : again sorry for the late response, it seems the problem comes from your python installation, the complaint is about non-existent `stdio.h` which is included by `Python.h`. Could you verify if `stdio.h` is present, and also check the version of Python installation?

**Comment by oshadura** [comment]
It looks like it is picking up wrong python (python 2.7 is system python on macos):
```
  │  ~/CERN_/xrootd/builds │   stable-5.3.x !1 ?1  python --version                                                      INT ✘ │ 16:25:53 
Python 3.9.6
  │  ~/CERN_/xrootd/builds │   stable-5.3.x !1 ?1  which python3                                                             ✔ │ 16:26:03 
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3

Adding -DPYTHON_EXECUTABLE:FILEPATH=/Library/Frameworks/Python.framework/Versions/3.9/bin/python3  didn't help in my case:
```
...
[100%] Generating python_bindings
XRootD library dir:     /Users/oshadura/CERN_sources/xrootd/builds/src
XRootD src include dir: /Users/oshadura/CERN_sources/xrootd/src
XRootD bin include dir: /Users/oshadura/CERN_sources/xrootd/builds/src
Version:                v20211129-e484f0e70
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py:507: UserWarning: The version specified ('v20211129-e484f0e70') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running build
running build_py
running build_ext
/Library/Developer/CommandLineTools/usr/bin/cc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g --std=c++0x -I/Users/oshadura/CERN_sources/xrootd/src -I/Users/oshadura/CERN_sources/xrootd/builds/src -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c /Users/oshadura/CERN_sources/xrootd/bindings/python/src/PyXRootDCopyProcess.cc -o build/temp.macosx-10.9-universal2-3.9/Users/oshadura/CERN_sources/xrootd/bindings/python/src/PyXRootDCopyProcess.o -g
In file included from /Users/oshadura/CERN_sources/xrootd/bindings/python/src/PyXRootDCopyProcess.cc:26:
In file included from /Users/oshadura/CERN_sources/xrootd/bindings/python/src/PyXRootDCopyProcess.hh:28:
In file included from /Users/oshadura/CERN_sources/xrootd/bindings/python/src/PyXRootD.hh:28:
In file included from /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/Python.h:25:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/stdio.h:107:15: fatal error: 'stdio.h' file not found
#include_next <stdio.h>
              ^~~~~~~~~
1 error generated.
error: command '/Library/Developer/CommandLineTools/usr/bin/cc' failed with exit code 1
make[2]: *** [bindings/python/python_bindings] Error 1
make[1]: *** [bindings/python/CMakeFiles/python_target.dir/all] Error 2
make: *** [all] Error 2
```
but adding `export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)` (https://stackoverflow.com/questions/51761599/cannot-find-stdio-h) finally helped...

**Comment by oshadura** [comment]
@simonmichal thanks a lot for a help, I closed issue since combination of macos/homebrew for xrootd build definitely works (but mac os itself seems to be a huge pain :D)
