### PR TITLE
OpenSSL 1.1 support

### PR DESCRIPTION
**Pull request by ellert**
Hi!
Here is my attempt at supporting OpenSSL 1.1.
It still compiles with OpenSSL 0.9.8e on RHEL 5 with the changes applied.
This obviously needs more testing than I am able to perform.

### CODE REVIEW

**Comment by ffurano** [comment]
Hi Mattias,

 I had a quick look at the mods in XrdHttp, and they make much sense to me. I'll try to look more carefully and test them in the next days or so. Thank you very much for the effort !

Fabrizio

**Comment by gganis** [comment]
Hi Mattias,
Thanks for providing the patch.
I have started checking your changes for openssl 1.1 . Hopefully I'll be done soon.

**Comment by ellert** [comment]
Any chance to get openssl 1.1 compatibility into 4.6.0?

**Comment by ljanyst** [comment]
Lack of support for new SSL breaks XRootD on Debian as well:

```
In file included from /home/ljanyst/Temp/xrootd/src/XrdCrypto/XrdCryptosslgsiAux.cc:39:0:
/usr/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
```

**Comment by gganis** [comment]
Hi,
Sorry for the late action.
I just did merge into the master.
For having it in the next 4.6.1, maybe this can be considered a bug fix, as there are no new features.
Andy? Michal?
I have checked that the patch is ok also for the stable-4.6.x branch .

**Comment by abh3** [comment]
Hi Gerri,

It's highly likely that will go into 4.6.1. Of course, Jenkins says it 
doesn't compile so there is some more work to do.

Andy
