### ISSUE TITLE
Build Fails on Centos7 with different exception specifier error

### ISSUE THREAD

**Issue by kgilje** [xrootd/xrootd#574]
I've been trying to get xrootd 4.3.0 installed on centos7 with gcc 4.8.5.  I've also tried installing xrootd 4.7.0 (in case my problem was addressed in a later version) with both gcc 4.8.5 and 5.4.0. I got passed the deprecated error/warnings referred to in issue 339 for xrootd 4.3.0 but then I came across an error similar to the following in BOTH 4.3.0 and 4.7.0 regardless of the compiler:
/path/to/xrootd/xrootd-4.7.0/src/XrdPosix/XrdPosixPreload.cc: In function ‘int access(const char*, int)’:
/path/to/xrootd/xrootd-4.7.0/src/XrdPosix/XrdPosixPreload.cc:59:39: error: declaration of ‘int access(const char*, int)’ has a different exception specifier
 int access(const char *path, int amode)
                                       ^
In file included from /path/to/xrootd/xrootd-4.7.0/src/XrdPosix/XrdPosixPreload.cc:33:0:
/path/to/system/include/unistd.h:290:12: error: from previous declaration ‘int access(const char*, int) throw ()’
 extern int access (const char *__name, int __type) __THROW __nonnull ((1));

 I am using cmake 3.7.2 and my cmake configuration looks as follows:
cmake ../xrootd-4.7.0 -DCMAKE_INSTALL_PREFIX=/path/to/xrootd/xrootd-4.7.0-install/ -DREADLINE_INCLUDE_DIR=/path/to/system/include/readline -DREADLINE_LIBRARY=/path/to/system/lib/libreadline.so
-- ----------------------------------------
-- Installation path: /path/to/xrootd/xrootd-4.7.0-install
-- C Compiler:        /path/to/system/gcc-5.4.0/bin/gcc
-- C++ Compiler:      /path/to/system/gcc-5.4.0/bin/g++
-- Build type:        RelWithDebInfo
-- Plug-in version:   4
-- 
-- Readline support:  yes
-- Fuse support:      disabled
-- Crypto support:    yes
-- Kerberos5 support: yes
-- XrdCl:             yes
-- Tests:             disabled
-- HTTP support:      yes
-- CEPH support:      disabled
-- Python support:    yes
-- ----------------------------------------

I'm working on an HPCC so I don't have much access to the internal workings of the system.
Please let me know if you would like any other information about the system or if you have a recommendation for what I should try.
Thanks

**Comment by simonmichal** [comment]
Hello,

Thanks for reporting this problem. Is it failing with both gcc 4.8.5 and 5.4.0?
Could you try to build with gcc 4.8.5 and cmake 2.8.12 (the defaults for centos 7) and let us know if it works?

Cheers,
Michal

**Comment by ljanyst** [comment]
It would seem your libc installation is broken. Are you cross-compiling?

**Comment by kgilje** [comment]
I'll have to reach out to the admins of the cluster.  I will let you know what happens. Thanks

**Comment by kgilje** [comment]
The Admins recommended building with the intel compiler instead of the gcc compiler.  I was able to install with icc and icpc 16.0.4 20160811.  Thank you for your help.

**Comment by simonmichal** [comment]
I suppose we can close this one?

Michal

**Comment by kgilje** [comment]
Yes,  the issue was with the environment on the cluster I'm using not xrootd.  Thanks for the help!
