### ISSUE TITLE
Compilation warning blocking build with GCC 8.1 [-Werror=stringop-truncation]

### ISSUE THREAD

**Issue by kgizdov** [xrootd/xrootd#702]
Hi,

I'm the package maintainer for Arch Linux and got this warning after the GCC 8.1 upgrade:
```cpp
/home/gizdov/Packages/builds/xrootd/src/xrootd-4.8.3/src/XrdApps/XrdCpFile.cc: In constructor ‘XrdCpFile::XrdCpFile(const char*, int&)’:
/home/gizdov/Packages/builds/xrootd/src/xrootd-4.8.3/src/XrdApps/XrdCpFile.cc:91:20: error: ‘char* strncpy(char*, const char*, size_t)’ output may be truncated copying 8 bytes from a string of length 8 [-Werror=stringop-truncation]
             strncpy(ProtName, pTab[i].pHdr, sizeof(ProtName));
             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
which prevents the build. I could override the `-Werror` flag, but I'd rather keep it as intended. For the moment, I have patched the issue with the following:
```diff
diff -aur xrootd-4.8.3-old/src/XrdApps/XrdCpFile.cc xrootd-4.8.3-new/src/XrdApps/XrdCpFile.cc
--- xrootd-4.8.3-old/src/XrdApps/XrdCpFile.cc	2018-05-13 19:01:03.602433537 +0200
+++ xrootd-4.8.3-new/src/XrdApps/XrdCpFile.cc	2018-05-13 19:01:48.269454421 +0200
@@ -88,7 +88,7 @@
    for (i = 0; i < pTnum; i++)
        {if (!strncmp(FSpec, pTab[i].pHdr, pTab[i].pHsz))
            {Protocol = pTab[i].pVal;
-            strncpy(ProtName, pTab[i].pHdr, pTab[i].pHsz-3);
+            memcpy(ProtName, pTab[i].pHdr, pTab[i].pHsz-3);
             return;
            }
        }
```

Just wanted to make sure this is appropriate and then I can submit a pull request.

Thanks.

**Comment by abh3** [comment]
Rats, I thought we caught all of these on our last big compile with gcc 8; apparently not. Thank you for catching this. Indeed, your proposal will work just as well.

**Comment by kgizdov** [comment]
I guess that closes it then.
