### ISSUE TITLE
Build fails with gcc 4.9.1 for Release build type

### ISSUE THREAD

**Issue by blinkseb** [xrootd/xrootd#226]
Hi,

I'm trying to build latest xrootd on my ubuntu machine (14.10), shipping with gcc 4.9.1. The build fails with the following error:

```
/home/sbrochet/build/xrootd-4.1.1/src/XrdXrootd/XrdXrootdJob.cc: In member function ‘void XrdXrootdJob2Do::delClient(XrdXrootdResponse*)’:
/home/sbrochet/build/xrootd-4.1.1/src/XrdXrootd/XrdXrootdJob.cc:261:69: error: array subscript is above array bounds [-Werror=array-bounds]
           {for (j = i+1; j < numClients; j++) Client[i++] = Client[j];
                                                                     ^
/home/sbrochet/build/xrootd-4.1.1/src/XrdXrootd/XrdXrootdJob.cc: In member function ‘int XrdXrootdJob2Do::verClient(int)’:
/home/sbrochet/build/xrootd-4.1.1/src/XrdXrootd/XrdXrootdJob.cc:327:71: error: array subscript is above array bounds [-Werror=array-bounds]
            for (j = i+1; j < numClients; j++,k++) Client[k] = Client[j];
                                                                       ^
```

I generate the Makefile with the following cmake command:

```
cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Release
```

It's interesting to notice that the build works when CMAKE_BUILD_TYPE is not specified.

Thanks

**Comment by ljanyst** [comment]
It works fine with 4.9.2 on Debian Testing. Can you re-try after dropping `DCMAKE_BUILD_TYPE=Release`? The intended and tested default is `RelWithDebInfo`. Please make sure to delete the build directory first as these variables get cached by CMake.

**Comment by blinkseb** [comment]
I tried a default build and it works fine, sorry for the noise here!

Thanks!

**Comment by ljanyst** [comment]
No problem. We see quite a bit compiler glitches. Closing.
